spring.application.name=labour-marketplace-backend
server.port=8081    
spring.datasource.url=jdbc:postgresql://localhost:5432/labourmarketplace
spring.datasource.username=postgres
spring.datasource.password=1245678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=SsN7YG2NDrvM4PnIjb14ANtflZwbroS3vQ2ElJh4jH9yJl1uHztfqdwwNe1fHWNI
jwt.expiration.ms=86400000
razorpay.key.id=rzp_test_TbFZ4AfNwiLS4h
razorpay.key.secret=5yeD45oc1xvf7HW7R1PAOG6h